### ISSUE TITLE
Include cloudinit.sh

### ISSUE THREAD

**Issue by colemickens** [yoctocloud/packer-archlinux#4]
https://github.com/yoctocloud/packer-archlinux/blob/master/scripts/cloudinit.sh

Can you include or copy that script? I'm curious what you do to configure cloudinit.

**Comment by vtolstov** [comment]
I'm include this script. But this is not original cloudinit, this is my handmade replacement written in go (forked from https://github.com/coreos/coreos-cloudinit)
